/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.liuxuan.THanalyzer.UI;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.liuxuan.THanalyzer.THAnalyzer;
import net.liuxuan.THanalyzer.conf.CONST;
import net.liuxuan.THanalyzer.conf.Parameters;

/**
 *
 * @author Administrator
 */
public class CommTypeSettingWindow extends javax.swing.JDialog {

    Parameters para;

    /**
     * Creates new form NewJDialog
     */
    public CommTypeSettingWindow(java.awt.Frame parent, boolean modal, Parameters para) {
        super(parent, modal);
        initComponents();
        this.para = para;
        init();
    }

    private void init() {
        setLocationRelativeTo(null);
        if (para.getCommType() == CONST.COMMTYPE_MODBUS) {
            jRadioButton_modbus.setSelected(true);
            jTabbedPane1.setSelectedIndex(0);
        } else if (para.getCommType() == CONST.COMMTYPE_T1L) {
            jRadioButton_t1.setSelected(true);
            jTabbedPane1.setSelectedIndex(1);
        } else {

        }
        jTextField_OwnerName.setText(para.getModbusinfo().getOwnerName());
        jFormattedTextField_SlaveAddr.setValue(para.getModbusinfo().getSlaveAddress());
        jFormattedTextField_TimeOut.setValue(para.getModbusinfo().getTimeout());
        jFormattedTextField_Interval.setValue(para.getInterval());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton_modbus = new javax.swing.JRadioButton();
        jRadioButton_t1 = new javax.swing.JRadioButton();
        jButton_ok = new javax.swing.JButton();
        jButton_cancle = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Modbus = new javax.swing.JPanel();
        jLabel_OwnerName = new javax.swing.JLabel();
        jTextField_OwnerName = new javax.swing.JTextField();
        jLabel_TimeOut = new javax.swing.JLabel();
        jFormattedTextField_TimeOut = new javax.swing.JFormattedTextField();
        jLabel_SlaveAddr = new javax.swing.JLabel();
        jFormattedTextField_SlaveAddr = new javax.swing.JFormattedTextField();
        jLabel_Interval = new javax.swing.JLabel();
        jFormattedTextField_Interval = new javax.swing.JFormattedTextField();
        jPanel_T1L = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("通讯类型设置");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(jRadioButton_modbus);
        jRadioButton_modbus.setSelected(true);
        jRadioButton_modbus.setText("调试室壁挂温湿度输出");
        jRadioButton_modbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_modbusActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_t1);
        jRadioButton_t1.setText("T1板 温湿度输出");
        jRadioButton_t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_t1ActionPerformed(evt);
            }
        });

        jButton_ok.setText("OK");
        jButton_ok.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton_ok.setMinimumSize(new java.awt.Dimension(81, 23));
        jButton_ok.setPreferredSize(new java.awt.Dimension(81, 23));
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jButton_cancle.setText("Cancle");
        jButton_cancle.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton_cancle.setMinimumSize(new java.awt.Dimension(81, 23));
        jButton_cancle.setPreferredSize(new java.awt.Dimension(81, 23));
        jButton_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_modbus)
                    .addComponent(jRadioButton_t1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_cancle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton_modbus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_t1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel_OwnerName.setText("主站名称：");

        jTextField_OwnerName.setText("MosesProducts.");

        jLabel_TimeOut.setText("超时设置：");

        jFormattedTextField_TimeOut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField_TimeOut.setText("500");

        jLabel_SlaveAddr.setText("从站地址：");

        jFormattedTextField_SlaveAddr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField_SlaveAddr.setText("1");
        jFormattedTextField_SlaveAddr.setPreferredSize(new java.awt.Dimension(24, 21));

        jLabel_Interval.setText("取点间隔：");

        jFormattedTextField_Interval.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField_Interval.setText("1000");
        jFormattedTextField_Interval.setToolTipText("应大于超时设置，否则会出现问题");
        jFormattedTextField_Interval.setEnabled(false);

        javax.swing.GroupLayout jPanel_ModbusLayout = new javax.swing.GroupLayout(jPanel_Modbus);
        jPanel_Modbus.setLayout(jPanel_ModbusLayout);
        jPanel_ModbusLayout.setHorizontalGroup(
            jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ModbusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_ModbusLayout.createSequentialGroup()
                        .addGroup(jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_OwnerName)
                            .addComponent(jLabel_TimeOut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_OwnerName, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField_TimeOut)))
                    .addGroup(jPanel_ModbusLayout.createSequentialGroup()
                        .addComponent(jLabel_SlaveAddr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField_SlaveAddr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_ModbusLayout.createSequentialGroup()
                        .addComponent(jLabel_Interval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField_Interval)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel_ModbusLayout.setVerticalGroup(
            jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ModbusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_OwnerName)
                    .addComponent(jTextField_OwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TimeOut)
                    .addComponent(jFormattedTextField_TimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SlaveAddr)
                    .addComponent(jFormattedTextField_SlaveAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ModbusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Interval)
                    .addComponent(jFormattedTextField_Interval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("壁挂", jPanel_Modbus);

        javax.swing.GroupLayout jPanel_T1LLayout = new javax.swing.GroupLayout(jPanel_T1L);
        jPanel_T1L.setLayout(jPanel_T1LLayout);
        jPanel_T1LLayout.setHorizontalGroup(
            jPanel_T1LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel_T1LLayout.setVerticalGroup(
            jPanel_T1LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("T1L板", jPanel_T1L);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        
        
        if (jRadioButton_modbus.isSelected()) {
            para.setCommType(CONST.COMMTYPE_MODBUS);
            try {
                jFormattedTextField_TimeOut.commitEdit();
                jFormattedTextField_SlaveAddr.commitEdit();
                Long timeout =  (Long) jFormattedTextField_TimeOut.getValue();
                Long slaveaddr =(Long) jFormattedTextField_SlaveAddr.getValue();
                para.getModbusinfo().setSlaveAddress(slaveaddr.intValue());
                para.getModbusinfo().setTimeout(timeout.intValue());
//                jFormattedTextField_Interval.commitEdit();
//                Long interval = (Long) jFormattedTextField_Interval.getValue();
//                para.getModbusinfo().setInterval(interval.intValue());
                if (jTextField_OwnerName.getText().length() > 0) {
                    para.getModbusinfo().setOwnerName(jTextField_OwnerName.getText());
                }
            } catch (ParseException ex) {
                Logger.getLogger(CommTypeSettingWindow.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jRadioButton_t1.isSelected()) {
            para.setCommType(CONST.COMMTYPE_T1L);
            
        } else {

        }

        para.save();

        this.dispose();
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jButton_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancleActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cancleActionPerformed

    private void jRadioButton_modbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_modbusActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jRadioButton_modbusActionPerformed

    private void jRadioButton_t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_t1ActionPerformed
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_jRadioButton_t1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_cancle;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JFormattedTextField jFormattedTextField_Interval;
    private javax.swing.JFormattedTextField jFormattedTextField_SlaveAddr;
    private javax.swing.JFormattedTextField jFormattedTextField_TimeOut;
    private javax.swing.JLabel jLabel_Interval;
    private javax.swing.JLabel jLabel_OwnerName;
    private javax.swing.JLabel jLabel_SlaveAddr;
    private javax.swing.JLabel jLabel_TimeOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Modbus;
    private javax.swing.JPanel jPanel_T1L;
    private javax.swing.JRadioButton jRadioButton_modbus;
    private javax.swing.JRadioButton jRadioButton_t1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_OwnerName;
    // End of variables declaration//GEN-END:variables
}
