/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.liuxuan.THanalyzer.UI;

import net.liuxuan.THanalyzer.conf.Parameters;

/**
 *
 * @author Administrator
 */
public class CommSettingWindow extends javax.swing.JDialog {

    String portName;
    int portNameNum;
    int baudRate;
    int stopBits;
    int dataBits;
    int parity;

    Parameters para;

    /**
     * Creates new form CommSettingWindow
     */
    public CommSettingWindow(java.awt.Frame parent, boolean modal, Parameters para) {
        super(parent, modal);
        initComponents();
        this.para = para;
        init();
    }

    private void init() {
        setLocationRelativeTo(null);
        portName = para.getSerialPort().getPortName();
        portNameNum = para.getSerialPort().getPortNameNum();

        baudRate = para.getSerialPort().getBaudRate();
        stopBits = para.getSerialPort().getStopBits();
        dataBits = para.getSerialPort().getDataBits();
        parity = para.getSerialPort().getParity();

        jComboBox_ComPort1.setSelectedItem(portName);
        jComboBox_BaudRate1.setSelectedItem("" + baudRate);
        jComboBox_Databits1.setSelectedItem("" + dataBits);
        jComboBox_Parity1.setSelectedIndex(parity);
        jComboBox_Stopbits1.setSelectedItem("" + stopBits);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_cancle = new javax.swing.JButton();
        jButton_ok = new javax.swing.JButton();
        jPanel_comportset1 = new javax.swing.JPanel();
        jLabel_ComPort1 = new javax.swing.JLabel();
        jComboBox_ComPort1 = new javax.swing.JComboBox();
        jLabel_BaudRate1 = new javax.swing.JLabel();
        jComboBox_BaudRate1 = new javax.swing.JComboBox();
        jLabel_Databits1 = new javax.swing.JLabel();
        jComboBox_Databits1 = new javax.swing.JComboBox();
        jLabel_Parity1 = new javax.swing.JLabel();
        jComboBox_Parity1 = new javax.swing.JComboBox();
        jLabel_Stopbits1 = new javax.swing.JLabel();
        jComboBox_Stopbits1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("串口设定");

        jButton_cancle.setText("CANCEL");
        jButton_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancleActionPerformed(evt);
            }
        });

        jButton_ok.setText("OK");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jPanel_comportset1.setBorder(javax.swing.BorderFactory.createTitledBorder("串口1设置"));

        jLabel_ComPort1.setText("串口设置：");

        jComboBox_ComPort1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM10", "COM11", "COM12", "COM13", "COM14", "COM15", "COM16", "COM17", "COM18", "COM19", "COM20", "COM21", "COM22", "COM23", "COM24", "COM25", "COM26", "COM27", "COM28", "COM29", "COM30", "COM31", "COM32" }));
        jComboBox_ComPort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ComPort1ActionPerformed(evt);
            }
        });

        jLabel_BaudRate1.setText("波特率：");

        jComboBox_BaudRate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "110", "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "38400", "43000", "56000", "57600", "115200" }));
        jComboBox_BaudRate1.setSelectedIndex(6);
        jComboBox_BaudRate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_BaudRate1ActionPerformed(evt);
            }
        });

        jLabel_Databits1.setText("数据位：");

        jComboBox_Databits1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "7", "8" }));
        jComboBox_Databits1.setSelectedIndex(2);
        jComboBox_Databits1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Databits1ActionPerformed(evt);
            }
        });

        jLabel_Parity1.setText("校验位：");

        jComboBox_Parity1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "ODD", "EVEN" }));
        jComboBox_Parity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Parity1ActionPerformed(evt);
            }
        });

        jLabel_Stopbits1.setText("停止位：");

        jComboBox_Stopbits1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jComboBox_Stopbits1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Stopbits1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_comportset1Layout = new javax.swing.GroupLayout(jPanel_comportset1);
        jPanel_comportset1.setLayout(jPanel_comportset1Layout);
        jPanel_comportset1Layout.setHorizontalGroup(
            jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Stopbits1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Databits1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Parity1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_BaudRate1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_ComPort1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox_Parity1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Stopbits1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_BaudRate1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_ComPort1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Databits1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel_comportset1Layout.setVerticalGroup(
            jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_ComPort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ComPort1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_BaudRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_BaudRate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Parity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Parity1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Databits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Databits1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Stopbits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Stopbits1))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_comportset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_comportset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ok)
                    .addComponent(jButton_cancle))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancleActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cancleActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        para.getSerialPort().setBaudRate(baudRate);
        para.getSerialPort().setDataBits(dataBits);
        para.getSerialPort().setParity(parity);
        para.getSerialPort().setPortName(portName);
        para.getSerialPort().setPortNameNum(portNameNum);
        para.getSerialPort().setStopBits(stopBits);
        para.save();
        this.dispose();
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jComboBox_ComPort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ComPort1ActionPerformed
        this.portName = (String) jComboBox_ComPort1.getSelectedItem();
        this.portNameNum = jComboBox_ComPort1.getSelectedIndex();
    }//GEN-LAST:event_jComboBox_ComPort1ActionPerformed

    private void jComboBox_BaudRate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_BaudRate1ActionPerformed
        //        this.baudRate = (int) jComboBox_BaudRate1.getSelectedIndex();
        this.baudRate = Integer.parseInt((String) jComboBox_BaudRate1.getSelectedItem());
    }//GEN-LAST:event_jComboBox_BaudRate1ActionPerformed

    private void jComboBox_Databits1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Databits1ActionPerformed
        //       this.dataBits = (int) jComboBox_Databits1.getSelectedIndex();
        this.dataBits = Integer.parseInt((String) jComboBox_Databits1.getSelectedItem());
    }//GEN-LAST:event_jComboBox_Databits1ActionPerformed

    private void jComboBox_Parity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Parity1ActionPerformed
        this.parity = jComboBox_Parity1.getSelectedIndex();
    }//GEN-LAST:event_jComboBox_Parity1ActionPerformed

    private void jComboBox_Stopbits1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Stopbits1ActionPerformed
        //         this.stopBits = (int) jComboBox_Stopbits1.getSelectedIndex();
        this.stopBits = Integer.parseInt((String) jComboBox_Stopbits1.getSelectedItem());
    }//GEN-LAST:event_jComboBox_Stopbits1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancle;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JComboBox jComboBox_BaudRate1;
    private javax.swing.JComboBox jComboBox_ComPort1;
    private javax.swing.JComboBox jComboBox_Databits1;
    private javax.swing.JComboBox jComboBox_Parity1;
    private javax.swing.JComboBox jComboBox_Stopbits1;
    private javax.swing.JLabel jLabel_BaudRate1;
    private javax.swing.JLabel jLabel_ComPort1;
    private javax.swing.JLabel jLabel_Databits1;
    private javax.swing.JLabel jLabel_Parity1;
    private javax.swing.JLabel jLabel_Stopbits1;
    private javax.swing.JPanel jPanel_comportset1;
    // End of variables declaration//GEN-END:variables
}
